### ISSUE TITLE
Getting `uninitialized constant Celluloid::FSM (NameError)` after requiring airplay at all

### ISSUE THREAD

**Issue by immjs** [elcuervo/airplay#100]
Hello!

I can't seem to require airplay at all. Please bear with me as I am new to the gem ecosystem but whatever depencency I try to downgrade, this error doesn't seem to go away.

Any help is appreciated, thanks in advance!

**Comment by carlhoerberg** [comment]
Same: 

```
✗ gem install airplay-cli
...
✗ air list
/home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/reel-0.5.0/lib/reel/request/state_machine.rb:5:in `<class:StateMachine>': uninitialized constant Celluloid::FSM (NameError)

      include Celluloid::FSM
                       ^^^^^
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/reel-0.5.0/lib/reel/request/state_machine.rb:4:in `<class:Request>'
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/reel-0.5.0/lib/reel/request/state_machine.rb:2:in `<module:Reel>'
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/reel-0.5.0/lib/reel/request/state_machine.rb:1:in `<top (required)>'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/reel-0.5.0/lib/reel/request.rb:6:in `<top (required)>'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/reel-0.5.0/lib/reel/connection.rb:1:in `<top (required)>'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/reel-0.5.0/lib/reel.rb:9:in `<top (required)>'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/reel-rack-0.2.3/lib/reel/rack/server.rb:3:in `<top (required)>'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/reel-rack-0.2.3/lib/rack/handler/reel.rb:1:in `<top (required)>'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/reel-rack-0.2.3/lib/reel/rack.rb:2:in `<top (required)>'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/airplay-1.0.5/lib/airplay/server.rb:4:in `<top (required)>'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/airplay-1.0.5/lib/airplay/player.rb:8:in `<top (required)>'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/airplay-1.0.5/lib/airplay/playable.rb:1:in `<top (required)>'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/airplay-1.0.5/lib/airplay/device.rb:2:in `<top (required)>'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/airplay-1.0.5/lib/airplay/devices.rb:2:in `<top (required)>'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/airplay-1.0.5/lib/airplay/browser.rb:5:in `<top (required)>'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/airplay-1.0.5/lib/airplay.rb:2:in `<top (required)>'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/airplay-1.0.5/lib/airplay/cli.rb:2:in `<top (required)>'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/airplay-cli-1.0.3/bin/air:4:in `<top (required)>'
        from /home/carl/.rbenv/versions/3.1.2/bin/air:25:in `load'
        from /home/carl/.rbenv/versions/3.1.2/bin/air:25:in `<main>'
```

**Comment by carlhoerberg** [comment]
Same: 

```
✗ gem install airplay-cli
...
✗ air list
/home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/reel-0.5.0/lib/reel/request/state_machine.rb:5:in `<class:StateMachine>': uninitialized constant Celluloid::FSM (NameError)

      include Celluloid::FSM
                       ^^^^^
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/reel-0.5.0/lib/reel/request/state_machine.rb:4:in `<class:Request>'
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/reel-0.5.0/lib/reel/request/state_machine.rb:2:in `<module:Reel>'
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/reel-0.5.0/lib/reel/request/state_machine.rb:1:in `<top (required)>'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/reel-0.5.0/lib/reel/request.rb:6:in `<top (required)>'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/reel-0.5.0/lib/reel/connection.rb:1:in `<top (required)>'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/reel-0.5.0/lib/reel.rb:9:in `<top (required)>'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/reel-rack-0.2.3/lib/reel/rack/server.rb:3:in `<top (required)>'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/reel-rack-0.2.3/lib/rack/handler/reel.rb:1:in `<top (required)>'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/reel-rack-0.2.3/lib/reel/rack.rb:2:in `<top (required)>'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/airplay-1.0.5/lib/airplay/server.rb:4:in `<top (required)>'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/airplay-1.0.5/lib/airplay/player.rb:8:in `<top (required)>'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/airplay-1.0.5/lib/airplay/playable.rb:1:in `<top (required)>'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/airplay-1.0.5/lib/airplay/device.rb:2:in `<top (required)>'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/airplay-1.0.5/lib/airplay/devices.rb:2:in `<top (required)>'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/airplay-1.0.5/lib/airplay/browser.rb:5:in `<top (required)>'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/airplay-1.0.5/lib/airplay.rb:2:in `<top (required)>'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/airplay-1.0.5/lib/airplay/cli.rb:2:in `<top (required)>'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/carl/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/carl/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/airplay-cli-1.0.3/bin/air:4:in `<top (required)>'
        from /home/carl/.rbenv/versions/3.1.2/bin/air:25:in `load'
        from /home/carl/.rbenv/versions/3.1.2/bin/air:25:in `<main>'
```

**Comment by fbi007130** [comment]
some libs should be download in gem,such as rack,celluloid and net-http.
I think the lib timeout should be downgrade to 0.0.1 but it is not possible because the version has been yank.
