### ISSUE TITLE
Crash in dnssd

### ISSUE THREAD

**Issue by tazjin** [elcuervo/airplay#75]
Hej!

When I try to run any airplay-cli command (e.g. `air list`) I get an immediate crash in dnssd.

```
> air list
D, [2014-02-02T15:07:18.330339 #13842] DEBUG -- : Terminating 4 actors...
/home/vincent/.gem/ruby/2.1.0/gems/dnssd-2.0/lib/dnssd/service.rb:64:in `_browse': DNSSD operation failed with unrecognized error code: -65537 (DNSSD::UnknownError)
    from /home/vincent/.gem/ruby/2.1.0/gems/dnssd-2.0/lib/dnssd/service.rb:64:in `browse'
    from /home/vincent/.gem/ruby/2.1.0/gems/dnssd-2.0/lib/dnssd.rb:178:in `run'
    from /home/vincent/.gem/ruby/2.1.0/gems/dnssd-2.0/lib/dnssd.rb:86:in `browse!'
    from /home/vincent/.gem/ruby/2.1.0/gems/airplay-1.0.2/lib/airplay/browser.rb:25:in `block in browse'
    from /usr/lib/ruby/2.1.0/timeout.rb:82:in `block in timeout'
    from /usr/lib/ruby/2.1.0/timeout.rb:70:in `catch'
    from /usr/lib/ruby/2.1.0/timeout.rb:70:in `timeout'
    from /usr/lib/ruby/2.1.0/timeout.rb:111:in `timeout'
    from /home/vincent/.gem/ruby/2.1.0/gems/airplay-1.0.2/lib/airplay/browser.rb:24:in `browse'
    from /home/vincent/.gem/ruby/2.1.0/gems/airplay-1.0.2/lib/airplay.rb:34:in `browse'
    from /home/vincent/.gem/ruby/2.1.0/gems/airplay-1.0.2/lib/airplay.rb:62:in `devices'
    from /home/vincent/.gem/ruby/2.1.0/gems/airplay-1.0.2/lib/airplay/cli.rb:46:in `list'
    from /home/vincent/.gem/ruby/2.1.0/gems/clap-1.0.0/lib/clap.rb:35:in `call'
    from /home/vincent/.gem/ruby/2.1.0/gems/clap-1.0.0/lib/clap.rb:35:in `run'
    from /home/vincent/.gem/ruby/2.1.0/gems/clap-1.0.0/lib/clap.rb:6:in `run'
    from /home/vincent/.gem/ruby/2.1.0/gems/airplay-cli-1.0.1/bin/air:8:in `<top (required)>'
    from /home/vincent/bin/air:23:in `load'
    from /home/vincent/bin/air:23:in `<main>'
```

Bonjour service discovery through something like `avahi-discover-standalone` works fine:
![bonjour](https://f.cloud.github.com/assets/1552853/2060377/efafcbd8-8c13-11e3-8f2e-680adc8f8a95.png)

This could be related to [this issue](https://github.com/tenderlove/dnssd/issues/7) in dnssd which seems to have the same error code, and [this issue](https://github.com/elcuervo/airplay/issues/62) in this project. There doesn't seem to be a dot in any of the result names though.

Cheers,
Vincent

**Comment by Aesthetikx** [comment]
As an anecdote, on FreeBSD I was seeing this error as well, but after reading this: https://www.mythtv.org/wiki/AirTunes/AirPlay#Not_seeing_AirPlay_device_in_iTunes it turns out that DNSSerivceBrowse returns -65537 when the avahi daemon is not running, so this was fixed by starting the avahi-daemon service. Not sure why it wouldn't return kDNSServiceErr_ServiceNotRunning instead?
