### ISSUE TITLE
`air list` causes "ERROR persistent: Net::PTTH crashed!"

### ISSUE THREAD

**Issue by C-Duv** [elcuervo/airplay#77]
On a _freshly_ installed Debian VM I can't get to list AirPlay devices as I get:

ERROR persistent: Net::PTTH crashed!
SocketError: getaddrinfo: Name or service not known

Is there something trivially forgotten when running airplay on a fresh Debian install?

Here is full output:

```
root@debian:~# air list
ERROR persistent: Net::PTTH crashed!
SocketError: getaddrinfo: Name or service not known
        /var/lib/gems/1.9.1/gems/net-ptth-0.0.17/lib/net/ptth/socket.rb:47:in `initialize'
        /var/lib/gems/1.9.1/gems/net-ptth-0.0.17/lib/net/ptth/socket.rb:47:in `new'
        /var/lib/gems/1.9.1/gems/net-ptth-0.0.17/lib/net/ptth/socket.rb:47:in `raw_socket'
        /var/lib/gems/1.9.1/gems/net-ptth-0.0.17/lib/net/ptth/socket.rb:16:in `write'
        /var/lib/gems/1.9.1/gems/net-ptth-0.0.17/lib/net/ptth.rb:78:in `request'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:67:in `dispatch'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
ERROR persistent: Net::PTTH crashed!
SocketError: getaddrinfo: Name or service not known
        /var/lib/gems/1.9.1/gems/net-ptth-0.0.17/lib/net/ptth/socket.rb:47:in `initialize'
        /var/lib/gems/1.9.1/gems/net-ptth-0.0.17/lib/net/ptth/socket.rb:47:in `new'
        /var/lib/gems/1.9.1/gems/net-ptth-0.0.17/lib/net/ptth/socket.rb:47:in `raw_socket'
        /var/lib/gems/1.9.1/gems/net-ptth-0.0.17/lib/net/ptth/socket.rb:16:in `write'
        /var/lib/gems/1.9.1/gems/net-ptth-0.0.17/lib/net/ptth.rb:78:in `request'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:67:in `dispatch'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
ERROR persistent: Airplay::Connection crashed!
SocketError: getaddrinfo: Name or service not known
        /var/lib/gems/1.9.1/gems/net-ptth-0.0.17/lib/net/ptth/socket.rb:47:in `initialize'
        /var/lib/gems/1.9.1/gems/net-ptth-0.0.17/lib/net/ptth/socket.rb:47:in `new'
        /var/lib/gems/1.9.1/gems/net-ptth-0.0.17/lib/net/ptth/socket.rb:47:in `raw_socket'
        /var/lib/gems/1.9.1/gems/net-ptth-0.0.17/lib/net/ptth/socket.rb:16:in `write'
        /var/lib/gems/1.9.1/gems/net-ptth-0.0.17/lib/net/ptth.rb:78:in `request'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:67:in `dispatch'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
        (celluloid):0:in `remote procedure call'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:92:in `value'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
        /var/lib/gems/1.9.1/gems/airplay-1.0.2/lib/airplay/connection/persistent.rb:39:in `request'
        /var/lib/gems/1.9.1/gems/airplay-1.0.2/lib/airplay/connection.rb:113:in `send_request'
        /var/lib/gems/1.9.1/gems/airplay-1.0.2/lib/airplay/connection.rb:80:in `get'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:67:in `dispatch'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
ERROR persistent: Airplay::Connection crashed!
SocketError: getaddrinfo: Name or service not known
        /var/lib/gems/1.9.1/gems/net-ptth-0.0.17/lib/net/ptth/socket.rb:47:in `initialize'
        /var/lib/gems/1.9.1/gems/net-ptth-0.0.17/lib/net/ptth/socket.rb:47:in `new'
        /var/lib/gems/1.9.1/gems/net-ptth-0.0.17/lib/net/ptth/socket.rb:47:in `raw_socket'
        /var/lib/gems/1.9.1/gems/net-ptth-0.0.17/lib/net/ptth/socket.rb:16:in `write'
        /var/lib/gems/1.9.1/gems/net-ptth-0.0.17/lib/net/ptth.rb:78:in `request'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:67:in `dispatch'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
        (celluloid):0:in `remote procedure call'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:92:in `value'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
        /var/lib/gems/1.9.1/gems/airplay-1.0.2/lib/airplay/connection/persistent.rb:39:in `request'
        /var/lib/gems/1.9.1/gems/airplay-1.0.2/lib/airplay/connection.rb:113:in `send_request'
        /var/lib/gems/1.9.1/gems/airplay-1.0.2/lib/airplay/connection.rb:80:in `get'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:67:in `dispatch'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
        /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
/var/lib/gems/1.9.1/gems/net-ptth-0.0.17/lib/net/ptth/socket.rb:47:in `initialize': getaddrinfo: Name or service not known (SocketError)
        from /var/lib/gems/1.9.1/gems/net-ptth-0.0.17/lib/net/ptth/socket.rb:47:in `new'
        from /var/lib/gems/1.9.1/gems/net-ptth-0.0.17/lib/net/ptth/socket.rb:47:in `raw_socket'
        from /var/lib/gems/1.9.1/gems/net-ptth-0.0.17/lib/net/ptth/socket.rb:16:in `write'
        from /var/lib/gems/1.9.1/gems/net-ptth-0.0.17/lib/net/ptth.rb:78:in `request'
        from /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
        from /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
        from /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:67:in `dispatch'
        from /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
        from /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
        from /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
        from /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
        from (celluloid):0:in `remote procedure call'
        from /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:92:in `value'
        from /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
        from /var/lib/gems/1.9.1/gems/airplay-1.0.2/lib/airplay/connection/persistent.rb:39:in `request'
        from /var/lib/gems/1.9.1/gems/airplay-1.0.2/lib/airplay/connection.rb:113:in `send_request'
        from /var/lib/gems/1.9.1/gems/airplay-1.0.2/lib/airplay/connection.rb:80:in `get'
        from /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
        from /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
        from /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:67:in `dispatch'
        from /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
        from /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
        from /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
        from /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
        from (celluloid):0:in `remote procedure call'
        from /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:92:in `value'
        from /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
        from /var/lib/gems/1.9.1/gems/airplay-1.0.2/lib/airplay/device.rb:125:in `basic_info'
        from /var/lib/gems/1.9.1/gems/airplay-1.0.2/lib/airplay/device.rb:86:in `server_info'
        from /var/lib/gems/1.9.1/gems/airplay-1.0.2/lib/airplay/device/info.rb:12:in `initialize'
        from /var/lib/gems/1.9.1/gems/airplay-1.0.2/lib/airplay/device.rb:78:in `new'
        from /var/lib/gems/1.9.1/gems/airplay-1.0.2/lib/airplay/device.rb:78:in `info'
        from /var/lib/gems/1.9.1/gems/airplay-1.0.2/lib/airplay/cli.rb:48:in `block in list'
        from /var/lib/gems/1.9.1/gems/airplay-1.0.2/lib/airplay/cli.rb:46:in `list'
        from /var/lib/gems/1.9.1/gems/clap-1.0.0/lib/clap.rb:35:in `call'
        from /var/lib/gems/1.9.1/gems/clap-1.0.0/lib/clap.rb:35:in `run'
        from /var/lib/gems/1.9.1/gems/clap-1.0.0/lib/clap.rb:6:in `run'
        from /var/lib/gems/1.9.1/gems/airplay-cli-1.0.1/bin/air:8:in `<top (required)>'
        from /usr/local/bin/air:23:in `load'
        from /usr/local/bin/air:23:in `<main>'
```

Versions used:
ruby v1.9.3p194
airplay gem v1.0.2, 0.2.9
airplay-cli gem v1.0.1
net-ptth gem v0.0.17
Debian v7.3

**Comment by priezz** [comment]
The problem is that local (not global) domains could not be resolved. To enable is in Arch Linux [nss-mdns](https://www.archlinux.org/packages/extra/x86_64/nss-mdns/) package is required. In Debian there should be something similar (rdnssd, I assume).

**Comment by varac** [comment]
Same error on ubuntu 16.04.

Local Domain is resolvable, and airplay service is found vy avahi:

```
--- airplay/airplayer ‹master* ⁇› » ping osmc.local
PING osmc.local (192.168.8.8) 56(84) bytes of data.
64 bytes from osmc (192.168.8.8): icmp_seq=1 ttl=64 time=2.64 ms
^C
--- osmc.local ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 2.643/2.643/2.643/0.000 ms

--- airplay/airplayer ‹master* ⁇› » avahi-browse _airplay._tcp
+  wlan0 IPv4 osmc                                          _airplay._tcp        local
```

What else can i try ?
