### ISSUE TITLE
TypeError: no implicit conversion of Symbol into Integer

### ISSUE THREAD

**Issue by bitboxer** [elcuervo/airplay#84]
Somehow I see the following error when trying to use air play with ruby 2.1.2:

```
ERROR celluloid: Reel::Rack::Server crashed!                                                                                                                     TypeError: no implicit conversion of Symbol into Integer
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/reel-0.5.0/lib/reel/server.rb:23:in `[]'
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/reel-0.5.0/lib/reel/server.rb:23:in `initialize'
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/reel-rack-0.1.0/lib/reel/rack/server.rb:20:in `initialize'
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:67:in `dispatch'
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
ERROR celluloid: Celluloid::SupervisionGroup crashed!
TypeError: no implicit conversion of Symbol into Integer
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/reel-0.5.0/lib/reel/server.rb:23:in `[]'
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/reel-0.5.0/lib/reel/server.rb:23:in `initialize'
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/reel-rack-0.1.0/lib/reel/rack/server.rb:20:in `initialize'
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:67:in `dispatch'
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
    (celluloid):0:in `remote procedure call'
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:92:in `value'
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/proxies/actor_proxy.rb:20:in `_send_'
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid.rb:200:in `new_link'
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/supervision_group.rb:136:in `start'
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/supervision_group.rb:124:in `initialize'
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/supervision_group.rb:82:in `new'
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/supervision_group.rb:82:in `add'
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/supervision_group.rb:73:in `supervise_as'
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:67:in `dispatch'
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
    /Users/bodo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
```

**Comment by elcuervo** [comment]
Can you give `1.0.5` a try please?
