### ISSUE TITLE
video can't be read

### ISSUE THREAD

**Issue by jeezs** [elcuervo/airplay#85]
hello, I try use airplay gem but on my set I experience lots of troubles.
First when trying to airplay image using ruby , the pictures send are not persistent , I have to set up a sleep just after using the view function.
Also when using ruby I have been unable to view movies.
My set up is a mac with Yosemite on it.
So I try on another computer with Maverick butI have the same problems with video and images.
Then I try using the terminal,then I obtain an error below.
Can you help? , Do you have any ideas?.

Thanks for help
MacBook-Air:airplay jeezs$ air play http://movietrailers.apple.com/movies/dreamworks/needforspeed/needforspeed-tlr1xxzzs2_480p.mov
Playing http://movietrailers.apple.com/movies/dreamworks/needforspeed/needforspeed-tlr1xxzzs2_480p.mov
ERROR persistent: Actor crashed!                             ] 0% Apple TV
CFFormatError: invalid XML: Start tag expected, '<' not found
    /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/CFPropertyList-2.2.8/lib/cfpropertylist/rbNokogiriParser.rb:25:in `rescue in load'
    /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/CFPropertyList-2.2.8/lib/cfpropertylist/rbNokogiriParser.rb:13:in`load'
    /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/CFPropertyList-2.2.8/lib/cfpropertylist/rbCFPropertyList.rb:313:in `load_str'
    /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/CFPropertyList-2.2.8/lib/cfpropertylist/rbCFPropertyList.rb:249:in`initialize'
    /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/airplay-1.0.3/lib/airplay/player.rb:144:in `new'
    /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/airplay-1.0.3/lib/airplay/player.rb:144:in`info'
    /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/airplay-1.0.3/lib/airplay/player.rb:248:in `block in check_for_playback_status'
    /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in`block in task'
    /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
    /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in`block in create'
ERROR persistent: Actor crashed!
CFFormatError: invalid XML: Start tag expected, '<' not found
    /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/CFPropertyList-2.2.8/lib/cfpropertylist/rbNokogiriParser.rb:25:in `rescue in load'
    /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/CFPropertyList-2.2.8/lib/cfpropertylist/rbNokogiriParser.rb:13:in`load'
    /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/CFPropertyList-2.2.8/lib/cfpropertylist/rbCFPropertyList.rb:313:in `load_str'
    /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/CFPropertyList-2.2.8/lib/cfpropertylist/rbCFPropertyList.rb:249:in`initialize'
    /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/airplay-1.0.3/lib/airplay/player.rb:144:in `new'
    /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/airplay-1.0.3/lib/airplay/player.rb:144:in`info'
    /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/airplay-1.0.3/lib/airplay/player.rb:248:in `block in check_for_playback_status'
    /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in`block in task'
    /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
    /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in`block in create'
/Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:34:in `terminate': task was terminated (Celluloid::Task::TerminatedError)
    from /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in`each'
    from /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `cleanup'
    from /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:329:in`shutdown'
    from /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:321:in `handle_crash'
    from /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:166:in`rescue in run'
    from /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:148:in `run'
    from /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:130:in`block in start'
    from /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
    from /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in`block in get_thread'
    from /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `call'
    from /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in`block in create'
    from (celluloid):0:in `remote procedure call'
    from /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in`value'
    from /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
    from /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/airplay-1.0.3/lib/airplay/cli.rb:90:in`play'
    from /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/airplay-cli-1.0.2/bin/air:29:in `block in <top (required)>'
    from /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/clap-1.0.0/lib/clap.rb:35:in`call'
    from /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/clap-1.0.0/lib/clap.rb:35:in `run'
    from /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/clap-1.0.0/lib/clap.rb:6:in`run'
    from /Users/jeezs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/airplay-cli-1.0.2/bin/air:8:in `<top (required)>'
    from /Users/jeezs/.rbenv/versions/2.1.2/bin/air:23:in`load'
    from /Users/jeezs/.rbenv/versions/2.1.2/bin/air:23:in `<main>'

**Comment by elcuervo** [comment]
Can you give `1.0.5` a try please? I want to resume work and that version seems to work.
