### ISSUE TITLE
Video doesn't play on Yosemite aka 10.10

### ISSUE THREAD

**Issue by bitboxer** [elcuervo/airplay#86]
I updated to yosemite on one of my computers and it can't play videos anymore. Pictures are shown without a problem.

This is the output of `air debug` :

```
This will run some basic tests on your network trying to find errors
and debug information to help fix them.

Running dns-sd tests:
Name: LtDoolittle
Host: 192.168.0.103
Port: 7000
Full Name: LtDoolittle._airplay._tcp.local.
Iface: en0
TXT: {"deviceid"=>"7C:D1:C3:0C:0C:8A", "features"=>"0x5A7FFFF7,0xE", "flags"=>"0x44", "model"=>"AppleTV3,1", "pk"=>"0a44638953b197db1988e1b2e934226853a39e9b090af3ae4a6d44b271a777c4", "srcvers"=>"210.98", "vv"=>"2"}

D, [2014-10-19T12:31:57.473543 #56731] DEBUG -- : Terminating 4 actors...
```

And this is the error I get: 

```
Playing example.mp4
ERROR persistent: Actor crashed!                                                                                               ] 0% LtDoolittle
Errno::ETIMEDOUT: Operation timed out - connect(2) for "192.168.0.106" port 62024
    /Users/bodo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/airplay-1.0.3/lib/airplay/server.rb:60:in `initialize'
    /Users/bodo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/airplay-1.0.3/lib/airplay/server.rb:60:in `new'
    /Users/bodo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/airplay-1.0.3/lib/airplay/server.rb:60:in `running?'
    /Users/bodo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/airplay-1.0.3/lib/airplay/server.rb:38:in `serve'
    /Users/bodo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
    /Users/bodo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
    /Users/bodo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
    /Users/bodo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
    /Users/bodo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
    /Users/bodo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
    /Users/bodo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
    /Users/bodo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
```

**Comment by elcuervo** [comment]
Can you give `1.0.5` a try please?
